# NumPy exercises

We are going to practice NumPy skills and basic syntax.

We put here also some examples that were not in the tutorial on purpose. Try to use google and offial NumPy documentation to solve these exercises.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [44]:
import numpy as np
import sys

#### 3. Create a null vector of size 10 (★☆☆)

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [13]:
array1 = np.zeros(10)
array1[4]  = 1
array1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [33]:
array2 = np.random.randint(10,50, size = 10)
array2

array([14, 10, 12, 24, 13, 40, 18, 43, 13, 36])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [35]:
array3 = np.flip(array2, axis=None)
array3

array([36, 13, 43, 18, 40, 13, 24, 12, 10, 14])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [25]:
array4 = np.random.randint(0,9, size=(3,3))
array4

array([[5, 7, 6],
       [5, 5, 6],
       [1, 0, 7]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [36]:
array5 = np.array([1,2,0,0,4,0])
result = np.where(array5 > 0)
print(result)

(array([0, 1, 4], dtype=int64),)


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [40]:
array6 =  np.random.randint(0,10, size=(3,3,3))
print(array6)

[[[8 4 5]
  [1 4 7]
  [1 7 8]]

 [[7 3 2]
  [6 9 7]
  [0 7 2]]

 [[6 3 2]
  [9 2 3]
  [4 6 4]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [49]:
array7 = np.random.randint(0,20, size=(10,10))
minnum = np.min(array7)
maxnum = np.max(array7)
print(minnum,maxnum)

0 19


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [54]:
array8 = np.random.randint(0,30, size=30)
mean = np.mean(array8)
print(mean)

14.433333333333334


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [59]:
array9 = np.ones((2,3))
array9[ 0:2, 1:2] = 0
array9

array([[1., 0., 1.],
       [1., 0., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [62]:
array10 = np.ones((3,3))
print(array10)
array10 = np.pad(array10, pad_width=1, mode='constant',
               constant_values=0)
print(array10)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [69]:
False

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [74]:
array11 = np.ones((5,5))
array11[[2,3,4], [1,2,3]] = [2,3,4]
array11

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 2., 1., 1., 1.],
       [1., 1., 3., 1., 1.],
       [1., 1., 1., 4., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [76]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [89]:
array12 = np.random.randint(0,25, size=(5,5))
print(np.linalg.norm(array12))


74.33034373659252


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [91]:
array13 = np.arange(11)
array13[(3 < array13) & (array13 < 8)] *= -1
print(array13)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
# I copy/pasted this because I have no idea what it means
Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))



#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
np.intersect1d
#just copied and pasted

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [94]:
np.sqrt(-1) == np.emath.sqrt(-1)
#apparently its not. no idea what this is/does

<ipython-input-94-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [103]:
def int_gen():
    for i in range(10):
       yield i
array14 = np.fromiter(int_gen(), dtype=float, count=-1)
array14

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [106]:
array15 = np.linspace(0,1,12,endpoint=False)[1:-1]
array15

array([0.08333333, 0.16666667, 0.25      , 0.33333333, 0.41666667,
       0.5       , 0.58333333, 0.66666667, 0.75      , 0.83333333])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [113]:
array16 = np.random.random(10)
array16.sort()
array16

array([0.16731239, 0.23161758, 0.24820319, 0.2575296 , 0.31219534,
       0.37437154, 0.38362112, 0.47636628, 0.64459299, 0.73636431])

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
#i just copied and pasted this because I have not been taught this yet
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [115]:
#copied and pasted again.
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.23481997 0.01037441 0.28973704 0.76780134 0.25355336 0.90314153
 0.         0.29937092 0.65620545 0.49093625]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
#copied and pasted. No idea what it means
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
#copied and pasted. No idea what it means
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

#### 59. How to sort an array by the nth column? (★★☆)

In [ ]:
#copied and pasted. No idea what it means
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
#copied and pasted. No idea what it means
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
#copied and pasted. No idea what it means
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

#### 72. How to swap two rows of an array? (★★★)

In [ ]:
#copied and pasted. No idea what it means
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [ ]:
#copied and pasted. No idea what it means
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

#### 83. How to find the most frequent value in an array?

In [ ]:
#copied and pasted. No idea what it means
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

#### 89. How to get the n largest values of an array (★★★)

In [ ]:
#copied and pasted. No idea what it means
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [ ]:
#copied and pasted. No idea what it means
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

uZ = np.unique(Z, axis=0)
print(uZ)